"""add job_preferences to user_settings

Revision ID: 0c9e4faa311b
Revises: ada0c4cd2b2f
Create Date: 2026-08-14 11:36:56.294205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c9e4faa311b'
down_revision: Union[str, Sequence[str], None] = 'ada0c4cd2b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_settings',
        sa.Column(
            'job_preferences',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='{"target_titles": [], "locations": [], "target_countries": ["IN"], '
            '"ctc_min": null, "ctc_max": null, "industries": [], "company_size_bands": [], '
            '"blocklist_companies": []}',
        ),
    )
    op.alter_column('user_settings', 'job_preferences', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'job_preferences')
    # ### end Alembic commands ###
