"""add answer_bank table

Revision ID: 4c14b767daf3
Revises: bbdba555faf3
Create Date: 2026-08-14 13:42:43.144298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c14b767daf3'
down_revision: Union[str, Sequence[str], None] = 'bbdba555faf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_bank',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('semantic_key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('policy', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'semantic_key')
    )
    op.create_index(op.f('ix_answer_bank_user_id'), 'answer_bank', ['user_id'], unique=False)
    # NOTE: autogenerate wants to drop ix_jobs_jd_embedding_hnsw here because
    # it was created via raw op.execute() (migration bbdba555faf3), not a
    # SQLAlchemy Index() the model layer knows about — that's a false
    # positive, intentionally not applied.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_bank_user_id'), table_name='answer_bank')
    op.drop_table('answer_bank')
    # ### end Alembic commands ###
