"""add match_scores table, calibration_count

Revision ID: 534576d38340
Revises: 4c14b767daf3
Create Date: 2026-08-14 14:34:20.145127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '534576d38340'
down_revision: Union[str, Sequence[str], None] = '4c14b767daf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_scores',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hard_filter_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('threshold_at_time', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id')
    )
    op.create_index(op.f('ix_match_scores_job_id'), 'match_scores', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_scores_user_id'), 'match_scores', ['user_id'], unique=False)
    # NOTE: autogenerate wants to drop ix_jobs_jd_embedding_hnsw here — same
    # false positive as migration 4c14b767daf3 (raw op.execute() index, not
    # visible to the model layer). Intentionally not applied.
    op.add_column(
        'user_settings',
        sa.Column('calibration_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('user_settings', 'calibration_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'calibration_count')
    op.drop_index(op.f('ix_match_scores_user_id'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_job_id'), table_name='match_scores')
    op.drop_table('match_scores')
    # ### end Alembic commands ###
