"""add countries to jobs

Revision ID: 60ac60970371
Revises: 0c9e4faa311b
Create Date: 2026-08-14 11:41:00.943871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60ac60970371'
down_revision: Union[str, Sequence[str], None] = '0c9e4faa311b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'jobs',
        sa.Column('countries', sa.ARRAY(sa.String()), nullable=False, server_default='{}'),
    )
    op.alter_column('jobs', 'countries', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'countries')
    # ### end Alembic commands ###
