"""add jd_embedding to jobs

Revision ID: bbdba555faf3
Revises: 60ac60970371
Create Date: 2026-08-14 12:20:58.220733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bbdba555faf3'
down_revision: Union[str, Sequence[str], None] = '60ac60970371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('jd_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###
    # HNSW index for cosine similarity search (spec §4 indexing note).
    op.execute(
        "CREATE INDEX ix_jobs_jd_embedding_hnsw ON jobs "
        "USING hnsw (jd_embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_jobs_jd_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'jd_embedding')
    # ### end Alembic commands ###
